// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "fedimint-react-native-bindings.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// Automated testing checks Java_com_fedimint_reactnative_ReactNativeBindingsModule and fedimint_reactnativebindings
// by comparing the whole line here.
/*
Java_com_fedimint_reactnative_ReactNativeBindingsModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return fedimint_reactnativebindings::multiply(a, b);
}
*/

// Installer coming from ReactNativeBindingsModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_com_fedimint_reactnative_ReactNativeBindingsModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    using JCallInvokerHolder = facebook::react::CallInvokerHolder;

    auto holderLocal = facebook::jni::make_local(callInvokerHolderJavaObj);
    auto holderRef = facebook::jni::static_ref_cast<JCallInvokerHolder::javaobject>(holderLocal);
    auto* holderCxx = holderRef->cthis();
    auto jsCallInvoker = holderCxx->getCallInvoker();
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);

    return fedimint_reactnativebindings::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_fedimint_reactnative_ReactNativeBindingsModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return fedimint_reactnativebindings::cleanupRustCrate(*runtime);
}