// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <fbjni/fbjni.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "fedimint-react-native-bindings.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// Automated testing checks Java_com_fedimint_reactnative_ReactNativeBindingsModule and fedimint_reactnativebindings
// by comparing the whole line here.
/*
Java_com_fedimint_reactnative_ReactNativeBindingsModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return fedimint_reactnativebindings::multiply(a, b);
}
*/

// Installer coming from ReactNativeBindingsModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_com_fedimint_reactnative_ReactNativeBindingsModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    // React Native 0.77+ uses fbjni HybridClass for CallInvokerHolder
    // Use the proper fbjni API to extract the CallInvoker
    auto callInvokerHolder = facebook::jni::wrap_alias(
        reinterpret_cast<facebook::react::CallInvokerHolder::javaobject>(callInvokerHolderJavaObj)
    )->cthis();
    auto jsCallInvoker = callInvokerHolder->getCallInvoker();

    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return fedimint_reactnativebindings::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_fedimint_reactnative_ReactNativeBindingsModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return fedimint_reactnativebindings::cleanupRustCrate(*runtime);
}