name: Build WASM
description: Builds the WASM bundle using Nix

runs:
  using: 'composite'
  steps:
    - uses: cachix/install-nix-action@V27
      with:
        nix_path: nixpkgs=channel:nixos-23.11
        extra_nix_config: |
          connect-timeout = 15
          stalled-download-timeout = 15

    - uses: cachix/cachix-action@v15
      with:
        name: fedimint
        authToken: ${{ inputs.cachix_auth_token }}

    - name: Build WASM
      shell: bash
      run: nix build -L .#wasmBundle

    - name: Copy WASM files
      shell: bash
      run: |
        cp result/share/fedimint-client-wasm/fedimint_* packages/wasm-bundler/
        cp result/share/fedimint-client-wasm-web/fedimint_* packages/wasm-web/
