// Generated by uniffi-bindgen-react-native
#include "fedimint-react-native-bindings.h"
#include "generated/fedimint_sdk.hpp"

namespace fedimint_reactnativebindings {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeFedimintSdk::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}