// swift-tools-version:5.9
import PackageDescription

// The Swift view of `rust/fedimint-sdk`'s `uniffi` feature. Both halves of the
// product are build outputs, not sources:
//
//   Sources/FedimintSdk/FedimintSdk.swift   generated by uniffi-bindgen
//   Frameworks/FedimintSdkFFI.xcframework   cross-compiled by cargo + xcodebuild
//
// Run `just build-swift` (scripts/build-ios-sdk.sh) before resolving this
// package; without the XCFramework the binary target below cannot be found.
let package = Package(
    name: "FedimintSdk",
    // macOS is supported on purpose, not incidentally: the XCFramework carries
    // a macos-arm64 slice so `swift test --package-path ios` runs on the host
    // with no simulator boot, which is what CI does. Both minimums have to
    // agree with IPHONEOS_/MACOSX_DEPLOYMENT_TARGET in
    // scripts/build-ios-lib.sh, which is what the C sources are compiled for.
    //
    // macOS here means **Apple Silicon only**. The XCFramework ships one
    // `macos-arm64` slice and no `x86_64` one, so an Intel Mac cannot resolve
    // the binary target — SwiftPM reports "no library for this platform was
    // found". SwiftPM has no way to say "macOS, arm64 only" in `platforms:`,
    // which is why it is said here instead.
    //
    // That is deliberate rather than an oversight: the macOS slice exists so
    // `swift test` runs on the host without booting a simulator, not because
    // macOS is a shipping target for this SDK. Adding the Intel slice would
    // mean a fifth cross-compile of the whole crate on every full build.
    platforms: [
        .iOS(.v15),
        .macOS(.v13),
    ],
    products: [
        .library(
            name: "FedimintSdk",
            targets: ["FedimintSdk"]
        )
    ],
    dependencies: [],
    targets: [
        // The static-library XCFramework. uniffi's generated Swift does
        // `import FedimintSdkFFI`, which resolves through the
        // `module.modulemap` inside each slice's Headers/ — that is also where
        // the `link framework "SystemConfiguration"` / `"Security"` lines come
        // from, so those two need no wiring here.
        .binaryTarget(
            name: "FedimintSdkFFI",
            path: "Frameworks/FedimintSdkFFI.xcframework"
        ),
        .target(
            name: "FedimintSdk",
            dependencies: ["FedimintSdkFFI"],
            path: "Sources/FedimintSdk",
            linkerSettings: [
                // rocksdb and aws-lc are C++, and a Rust `staticlib` — unlike a
                // `cdylib` — does not record its native library dependencies for
                // whoever links it. Without this the link fails on `___cxa_throw`,
                // `___gxx_personality_v0` and every rocksdb vtable.
                //
                // This is the Apple counterpart of the `libc++_shared.so` that
                // scripts/build-android-sdk.sh copies out of the NDK into jniLibs
                // for exactly the same reason. On Apple platforms libc++ ships
                // with the OS, so linking it is all that is needed — there is
                // nothing to bundle.
                .linkedLibrary("c++")
            ]
        ),
        .testTarget(
            name: "FedimintSdkTests",
            dependencies: ["FedimintSdk"],
            path: "Tests/FedimintSdkTests"
        ),
    ]
)
