// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "fedimint-react-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "FedimintReactNativeSpec.h"

@interface ReactNative : NSObject <NativeReactNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ReactNative : NSObject <RCTBridgeModule>
#endif

@end