name: Setup Nix
description: Sets up nix for running tests with devimint

inputs:
  cachix_auth_token:
    description: 'Cachix authentication token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@V27
      with:
        nix_path: nixpkgs=channel:nixos-23.11
        extra_nix_config: |
          connect-timeout = 15
          stalled-download-timeout = 15

    - name: Setup Cachix
      uses: cachix/cachix-action@v15
      with:
        name: fedimint
        authToken: ${{ inputs.cachix_auth_token }}
      continue-on-error: true
