name: Changesets

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml

  changesets:
    name: Publish Changesets
    # needs: verify
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build WASM
        uses: ./.github/actions/build-wasm

      - name: Setup Nix shell and run commands
        run: |
          nix develop --accept-flake-config --command bash << EOF
            # Install dependencies
            pnpm install

            # Build packages
            pnpm build

            # Run Tests
            pnpm test
          EOF

      - name: PR or Publish to NPM
        uses: changesets/action@v1
        with:
          publish: |
            nix develop --accept-flake-config --command bash << EOF
              pnpm release
            EOF
          createGithubReleases: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish prerelease
        # Only publish a prerelease if we didn't publish a release
        if: steps.changesets.outputs.published != 'true'
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          nix develop --accept-flake-config --command bash << EOF
            npm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN"
            git reset --hard origin/main
            pnpm clean
            pnpm changeset version --no-git-tag --snapshot canary
            pnpm build
            pnpm changeset publish --no-git-tag --snapshot canary --tag canary
          EOF
