# NO LONGER USED - the docs site is now being deployed to github pages instead of the example
name: Deploy Vite-Core Example to GitHub Pages

on:
  # Using github pages for docs instead of preview

  # push:
  # branches: ['main']
  # paths: ['packages/core-web/**', 'examples/vite-core/**']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Vite-Core Example to GitHub Pages
    environment:
      name: '@fedimint/core-web + Vite Example'
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build
        run: pnpm build && pnpm build:pages

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: 'examples/vite-core/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
