name: Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml

  size:
    name: Size
    runs-on: [self-hosted, linux]
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build WASM
        uses: ./.github/actions/build-wasm

      - name: Install dependencies and build packages
        run: |
          nix develop --accept-flake-config --command bash << EOF
            # Install dependencies
            pnpm install

            # Build packages
            pnpm build

          EOF

      - name: Report build size
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '{packages/**/dist/**/*.{js,mjs,cjs},packages/**/*.wasm}'
