name: Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml

  size:
    name: Size
    runs-on: [self-hosted, linux]
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build WASM
        uses: ./.github/actions/build-wasm

      - name: Report build size
        # Fork modifies build-script to run arbitrary buildScript instead of pnpm run ${buildScript}
        uses: alexlwn123/compressed-size-action@alex/fix-build
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '{packages/**/dist/**/*.{js,mjs,cjs},packages/**/*.wasm}'
          install-script: nix develop --accept-flake-config --command pnpm install
          build-script: nix develop --accept-flake-config --command pnpm build

      # https://github.com/actions/checkout/issues/692#issuecomment-1502203573
      - name: Cleanup checkout
        uses: actions/checkout@v4
