name: Snapshot
on:
  workflow_dispatch:

jobs:
  snapshot:
    name: Release snapshot version
    permissions:
      contents: write
      id-token: write
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build WASM
        uses: ./.github/actions/build-wasm

      - name: Install dependencies and build packages
        run: |
          pnpm install
          pnpm build

      - name: Publish Snapshot
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch=$(git branch --show-current)
          snapshot=$(echo $branch | tr -cs '[:alnum:]-' '-' | tr '[:upper:]' '[:lower:]' | sed 's/-$//')
          npm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN"
          git reset --hard origin/$branch
          pnpm clean
          pnpm changeset version --no-git-tag --snapshot $snapshot
          pnpm build
          pnpm changeset publish --no-git-tag --snapshot $snapshot --tag snapshot
