name: Verify
on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Lint repo
        run: pnpm lint:repo

      - name: Lint code
        run: pnpm lint

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build
        run: pnpm build

  types:
    name: Types
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Check types
        run: pnpm typecheck

  test:
    name: Test
    runs-on: [self-hosted, linux]
    timeout-minutes: 30

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Setup Nix shell and run commands
        run: |
          nix develop --accept-flake-config --command bash << EOF
            # Install dependencies
            pnpm install

            # Build packages
            pnpm build

            # Run Tests
            pnpm test
          EOF

  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build Packages (dependency of docs)
        run: pnpm build

      - name: Build Docs
        run: pnpm docs:build
