name: Verify
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-react-native:
    name: Build React Native
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build React Native
        uses: ./.github/actions/build-react-native

  lint:
    name: Lint
    needs: build-react-native
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Download Generated Bindings
        uses: actions/download-artifact@v4
        with:
          name: generated-bindings
          path: packages/react-native-bindings

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Lint repo
        run: pnpm lint:repo

      - name: Lint code
        run: pnpm lint

  build:
    name: Build JS
    needs: build-react-native
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Download Generated Bindings
        uses: actions/download-artifact@v4
        with:
          name: generated-bindings
          path: packages/react-native-bindings

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build
        run: pnpm build

  types:
    name: Check Types
    needs: build-react-native
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Download Generated Bindings
        uses: actions/download-artifact@v4
        with:
          name: generated-bindings
          path: packages/react-native-bindings

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build types package
        run: pnpm --filter @fedimint/types build

      - name: Check types
        run: pnpm typecheck

  test:
    name: Test
    needs: build-react-native
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 30

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Download Generated Bindings
        uses: actions/download-artifact@v4
        with:
          name: generated-bindings
          path: packages/react-native-bindings

      - name: Build WASM
        uses: ./.github/actions/build-wasm

      - name: Run pnpm tests
        shell: bash
        run: |
          set -euo pipefail

          # Install dependencies
          nix develop --accept-flake-config -c pnpm install

          # Build packages
          nix develop --accept-flake-config -c pnpm build

          # Run Tests
          nix develop --accept-flake-config .#wasm-tests -c pnpm test

      - name: Report Size
        uses: alexlwn123/compressed-size-action@alex/fix-build
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '{packages/**/dist/**/*.{js,mjs,cjs},packages/**/*.wasm}'
          install-script: pnpm install
          build-script: pnpm build

  build-docs:
    name: Build Docs
    needs: build-react-native
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Download Generated Bindings
        uses: actions/download-artifact@v4
        with:
          name: generated-bindings
          path: packages/react-native-bindings

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build Packages (dependency of docs)
        run: pnpm build

      - name: Build Docs
        run: pnpm docs:build
