name: Build React Native
description: Builds Android and iOS bindings using Nix
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: nix develop --accept-flake-config -c pnpm install --frozen-lockfile

    - name: Build iOS Bindings
      shell: bash
      working-directory: packages/react-native-bindings
      run: |
        nix develop --accept-flake-config ../../.#ios -c pnpm run ubrn:ios:release
        rm -rf ../../fedimint-sdk-ffi/fedimint-client-uniffi/target # Clean up cache
        nix store gc

    - name: Compress iOS binaries
      shell: bash
      working-directory: packages/react-native-bindings
      run: |
        nix develop ../../ -c zip -9 -r ios-artifacts.zip FedimintReactNativeBindingsFramework.xcframework
        IOS_SHA256=$(shasum -a 256 ios-artifacts.zip | cut -d' ' -f1)
        IOS_SIZE=$(du -h ios-artifacts.zip | cut -f1)
        echo "iOS checksum: $IOS_SHA256"
        echo "iOS size: $IOS_SIZE"
        echo "IOS_SHA256=$IOS_SHA256" >> $GITHUB_ENV
        echo "### iOS Artifacts" >> $GITHUB_STEP_SUMMARY
        echo "- Size: $IOS_SIZE" >> $GITHUB_STEP_SUMMARY
        echo "- SHA256: $IOS_SHA256" >> $GITHUB_STEP_SUMMARY

    - name: Build Android Bindings
      shell: bash
      working-directory: packages/react-native-bindings
      run: |
        nix develop --accept-flake-config ../../.#android -c pnpm run ubrn:android:release
        nix develop --accept-flake-config ../../.#android -c pnpm build
        rm -rf ../../fedimint-sdk-ffi/fedimint-client-uniffi/target # Clean up cache
        nix store gc

    - name: Compress Android binaries
      shell: bash
      working-directory: packages/react-native-bindings
      run: |
        nix develop --accept-flake-config ../../ -c zip -9 -r android-artifacts.zip android/src/main/jniLibs
        ANDROID_SHA256=$(shasum -a 256 android-artifacts.zip | cut -d' ' -f1)
        ANDROID_SIZE=$(du -h android-artifacts.zip | cut -f1)
        echo "Android checksum: $ANDROID_SHA256"
        echo "Android size: $ANDROID_SIZE"
        echo "ANDROID_SHA256=$ANDROID_SHA256" >> $GITHUB_ENV
        echo "### Android Artifacts" >> $GITHUB_STEP_SUMMARY
        echo "- Size: $ANDROID_SIZE" >> $GITHUB_STEP_SUMMARY
        echo "- SHA256: $ANDROID_SHA256" >> $GITHUB_STEP_SUMMARY

    - name: Upload Generated Bindings
      uses: actions/upload-artifact@v4
      with:
        name: generated-bindings
        path: |
          packages/react-native-bindings/src
          packages/react-native-bindings/android/src/main/jniLibs
          packages/react-native-bindings/FedimintReactNativeBindingsFramework.xcframework
          packages/react-native-bindings/lib
        if-no-files-found: error
